name: Azure Static Web Apps CI/CD

pr: # pull request
  branches:
    include:
      - master
trigger: #  triggers pipeline only works when there is any changes in master branch
  branches:
    include:
      - master

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: build_job
    displayName: Build Job
    pool: # Machine we are calling
      vmImage: ubuntu-latest # vmImage --> virtual machine Image
    steps:
    - checkout: self # checks out to the specific repo
      submodules: true # submodules --> folders
      # all the generated artifacts will be present in 'dist' folder
    # Add any build-related steps here

- stage: DeployToStaging
  displayName: Deploy to Staging Stage
  jobs:
  - job: deploy_to_staging_job
    displayName: Deploy to Staging Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
      submodules: true
    - task: AzureStaticWebApp@0      # defined keyword --> @0 indicates the version
      inputs:
        azure_static_web_apps_api_token: $(deployment_token)
        app_location: "/" # Specify the source code path --> root directory of the source codes
        api_location: "" # Api source code path - optional
        output_location: "dist" # Built app content directory - optional
        deployment_environment: 'staging' # Specify the deployment environment as staging
